image: node:8.14.1

pages:
  cache:
    paths:
    - node_modules/

  stage: deploy
  script:
  - npm install -g @angular/cli@7.1.1
  - npm install
  - ng build
  - mv dist/a-day-in-a-live/* public/
  artifacts:
    paths:
    - public
  only:
  - master
  - deploy